### ISSUE TITLE
can't find jar download

### ISSUE THREAD

**Issue by Tcll** [ChenThread/ctif#2]
your readme mentions using a jar but provides no resource link.

the threads provided link to an online converter with no jar download.

please provide the resource if you expect someone to download it.

**Comment by Tcll** [comment]
well after some nasty googling, i finally found the releases page.
https://github.com/ChenThread/ctif/releases

there's absolutely no reason the release page should be that difficult to find.

**Comment by asiekierka** [comment]
Why did you feel the need to Google? ~~As I told you~~ As I tried to tell you but my e-mail to GitHub didn't go through and, as such, the message was not posted here, it's right here on the main page:

![](http://img.asie.pl/54VD)

I couldn't make an image as I was travelling by bus and using image editors on a phone is anything but trivial.

The "Releases" module of GitHub is commonly used by a substantial amount of GitHub-hosted projects; it was my understanding that, being on the main page of the project, it'd be easy to find.

I additionally believe your hostility towards a non-profit, unmaintained project given "as-is" without any warranty is very much unwarranted, and a polite question would've worked much better.

**Comment by Tcll** [comment]
I'll be honest, I've never actually used that in all my years of using GitHub.
or rather, the few times I did, those projects never used it...
so I pretty much read the readme, or nearest websites first, and have basically forgotten about the tab.

thanks for trying to tell me BEFORE I made a fool of myself...
but you can't beat luck when it slaps you in the face. :P

**Comment by asiekierka** [comment]
@Tcll 

You haven't made a fool of yourself. You didn't know, and that's fine. The only mistake you have made is acting somewhat hostile towards a developer bringing you free software - please avoid doing that in the future, on any projects.

**Comment by Tcll** [comment]
lol sorry, guess I should stop playing games that put me in that sort of mindset huh XD

honestly, I felt like I was dealing with yet another person who was trying to make it hard for people to obtain their stuff.

sorry I misjudged :)

I should also mention, this stupid phone played my patients as well... :P
