### ISSUE TITLE
OC LuaJIT - Does not support bin ops

### ISSUE THREAD

**Issue by sigmasoldi3r** [ChenThread/ctif#5]
Binary operations are not supported directly in the version of LuaJIT that `OpenComputers` use at default.

This leads to the following error when executing the viewer:
```
/home/oc-viewer.lua:13; ')' expected near &
```

A version supporting that OC restriction could be added.

**Comment by sigmasoldi3r** [comment]
My bad, just seen that can be solved changing CPU's arch.

**Comment by asiekierka** [comment]
If you're willing to make a Lua 5.2-compatible version using bit32, that could also be handy.
